// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpafxofhnmttnhctecfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wYWZ4b2Zobm10dG5oY3RlY2Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjE0NjEsImV4cCI6MjA2MzkzNzQ2MX0.OepCHsCr3X_bVjIAD0XZEObmr0WwrKa1F8EAlyGddUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);